### ISSUE TITLE
Resellers

### ISSUE THREAD

**Issue by rleone70** [openvoips/OV500#10]
Hi,
if I add a reseller after filling in the required fields I get the 500 server unreachable error and it is no longer possible to consult or add.

thanks

**Comment by openvoips** [comment]
I have tested in demo http://openvoips.org/portal/resellers/add  url and it
is working. Can you let us know where you are doing this.  So, can help on
the issue.

**Comment by rleone70** [comment]
I installed ov500 on virtualbox with ISO centos 7 to try the product. I did it several times and every time I saved the reseller I got the page with error. I followed the installation guide

**Comment by openvoips** [comment]
Share the installation machine access.  may be i can help.
Skype: akumardayal

**Comment by rleone70** [comment]
I tried with another browser (firefox) and i get white screen - maybe the url can help

![white-screen](https://user-images.githubusercontent.com/60712607/74060932-4612c980-49eb-11ea-9245-06dd1a51e29d.png)

**Comment by openvoips** [comment]
git code is working on my machine. maybe the problem in installation or
give me access so i can helop.

**Comment by sanjay8090** [comment]
I have modified 
 https://github.com/openvoips/OV500/blob/master/portal/application/models/Reseller_mod.php  file to fix your data issue.  Use updated code of this file.

**Comment by rleone70** [comment]
Updated the reseller_mod file seems to work. I have another problem with the carrier registration: it does not make me select "Carrier tarif" and "provider" both boxes are empty.
![issues](https://user-images.githubusercontent.com/60712607/74087275-e79d2800-4a8a-11ea-966a-95fe5d192752.png)
![issues2](https://user-images.githubusercontent.com/60712607/74087300-11564f00-4a8b-11ea-98ea-e6950b3636ae.png)
Thanks

**Comment by kanand81** [comment]
please use the updated GUI.
