### ISSUE TITLE
Calls failing when using IP Auth in Customer

### ISSUE THREAD

**Issue by amitiyer** [openvoips/OV500#17]
Hello,

I am making a test call via IP auth and i receive 407, Proxy Authentication error. I have added the IP in the customer account.

**Comment by openvoips** [comment]
Share the sip log so we can help.

**Comment by amitiyer** [comment]
Please find the attached trace.

[testing.zip](https://github.com/openvoips/OV500/files/4225107/testing.zip)

**Comment by amitiyer** [comment]
can you please let me know what i am missing ?

**Comment by kanand81** [comment]
Packet is Ok and source IP address is 75.98.46.226 with dialing 999XXXXXXXXX. Here you need to check what dialing pattern is allowed in the customer config. Please can you let us know what setting you have  in client system from "fromdomain".

**Comment by amitiyer** [comment]
I have checked the dialing pattern, on the console i get this.

>  1(21727) ALERT: <script>: IPAUTH User Check: SELECT account.account_status, customer_sip_account.`status` device_status, media_transcoding, ipaddress, customer_sip_account.account_id, FIND_IN_SET('75.98.46.226',ipaddress) state,  FIND_IN_SET('75.98.46.226',ipaddress) state2, ipauthfrom, account.id user_id, account.account_cc, account.account_cps, customer_sip_account.id enddevice_id, customer_sip_account.sip_cc enddevice_cc, customer_sip_account.sip_cps enddevice_cps, account.media_rtpproxy user_withmedia,'u' dtype from customer_sip_account INNER JOIN  account on customer_sip_account.account_id = account.account_id where  username ='AGTEST' and account.account_type = 'CUSTOMER';
 1(21727) ALERT: <script>: Call from User name AGTEST <null> <null>
 1(21727) ALERT: <script>: INVITE IP AUTH Check :  SELECT account.account_status, ipauthfrom, customer_ips.ip_status device_status, media_transcoding, ipaddress, customer_ips.account_id, FIND_IN_SET('75.98.46.226',ipaddress) state,  FIND_IN_SET('75.98.46.226',ipaddress) state2, customer_ips.id enddevice_id, customer_ips.ip_cps enddevice_cps, customer_ips.ip_cc enddevice_cc, account.id user_id, account.account_cc, account.account_cps, account.media_rtpproxy user_withmedia,'ip' dtype from customer_ips  INNER JOIN account on account.account_id = customer_ips.account_id where  ipaddress = '75.98.46.226' and '17324367886' like dialprefix and account.account_type = 'CUSTOMER' ORDER BY dialprefix DESC limit 1; 
 1(21727) ALERT: <script>: Call from User name account  AGTEST IS000003994 5
 1(21727) ALERT: <script>: AA2  -- ACCOUNTCODE IS000003994  DEVICEID 5  DEVICECC 10 DEVICECPS 10 ACCOUNTID 2  ACCOUNTCC 100 ACCOUNTCPS 10  WITHMEDIA 0 
 1(21727) ALERT: <script>: m-line: c=IN IP4 122.170.29.116  122.170.29.116
 1(21727) ERROR: textopsx [textopsx.c:171]: msg_apply_changes_f(): cannot apply msg changes after adding record-route header - it breaks conditional 2nd header
 1(21727) ALERT: <script>: msg_apply_changes CALLS Route
 1(21727) ALERT: <script>: ----CPSLOG---------- IS000003994 : 10 COUNT 0  TIME  1582180977 
 1(21727) ALERT: <script>: AA3  -- ACCOUNTCODE IS000003994  DEVICEID 5  DEVICECC 10 DEVICECPS 10 ACCOUNTID 2  ACCOUNTCC 100 ACCOUNTCPS 10  WITHMEDIA 0

**Comment by kanand81** [comment]
configuration issue in the system. Need to check your system manually. please write  your issue to openvoips@gmail.com for support

**Comment by amitiyer** [comment]
I solved the issue, in the database the ipauth value was NO, i set it to From and the calls are passing.
Also i observed that the call is dropping at 32 seconds even when i call from the sip device. Is there any setting of NAT that i need to configure ?
