### ISSUE TITLE
No answered calls and ringing calls in live calls view

### ISSUE THREAD

**Issue by amitiyer** [openvoips/OV500#18]
when checking the live call stats can only see total concurrent and total progress cannot see total answered or total ringing calls.

**Comment by amitiyer** [comment]
any update ?

**Comment by kanand81** [comment]
can you check http://localhost/api/api.php URL is working in server?
--
Anand Kumar
Mobile: +919949800228

**Comment by amitiyer** [comment]
Yes, The URL is working on the server, Also i can see Total Concurrent and Total Progress calls. I cannot see total Ringing or Answered. 
I accessed the database and changed the stats from progress to answer manually on one live call in livecall table and i could see 1 answered call in the live dashboard. 
What i found is all the live calls status is progress in the database. when the call gets answered the status does not change it stays in progress itself i think that's why we are not getting the answered / ringing value in the live call dashboard.

**Comment by openvoips** [comment]
Update  portal/api/lib/OVS.php  file with the latest
https://github.com/openvoips/OV500/blob/master/portal/api/lib/OVS.php file
and check it. As per my understanding, the secure web server is configured
in your server and old OVS.php class using an unsecured web server API to
update the call status.

**Comment by amitiyer** [comment]
Sure, Let me check that and update you.
Thanks.
