### ISSUE TITLE
Ratecard type Carrier not adding

### ISSUE THREAD

**Issue by meshtask** [openvoips/OV500#19]
Whenever i try to add a ratecard of type Provider and press save button, its added but its type changes to Customer. is this anexpected behavior or is it a bug?

**Comment by kanand81** [comment]
When was  you download build?

**Comment by meshtask** [comment]
I installed it just yesterday by following the method listed on ov500 website.
This same thing is happening even with the demo site of ov500.

**Comment by openvoips** [comment]
I will verify again your concern. It should need to display as carrier type.

**Comment by sanjay8090** [comment]
use the updated code of https://github.com/openvoips/OV500/blob/master/portal/application/controllers/Ratecard.php   file.

**Comment by meshtask** [comment]
It's working fine now.
