### ISSUE TITLE
Install guide trouble !

### ISSUE THREAD

**Issue by Madji** [openvoips/OV500#2]
install -m 755  app_python3.so  /home/OV500/LB/lib64/kamailio/modules
Package json-c was not found in the pkg-config search path.
Perhaps you should add the directory containing `json-c.pc'
to the PKG_CONFIG_PATH environment variable
No package 'json-c' found
Package json-c was not found in the pkg-config search path.
Perhaps you should add the directory containing `json-c.pc'
to the PKG_CONFIG_PATH environment variable
No package 'json-c' found
CC (gcc) [M nsq.so]		nsq_reader.o
In file included from nsq_reader.c:28:0:
nsq_reader.h:30:18: фатальная ошибка: json.h: Нет такого файла или каталога
 #include <json.h>
    

Centos7 minimal

**Comment by Madji** [comment]
CC (gcc) [M nsq.so]		nsq_reader.o
In file included from nsq_reader.c:28:0:
nsq_reader.h:33:17: фатальная ошибка: nsq.h: Нет такого файла или каталога
 #include "nsq.h"

**Comment by Madji** [comment]
Completely not correct installation manual . 
1.According to this manual is not going to kamailo.
2.In the second step with the installation of mariadb should be the early item build kamailo. As with the lack of myqsl-devel, Camilo not be collected. 
Guys if uploaded the manual Assembly his project, then let he although would be the right. 
I specifically put centos 7 full, but..
 still not going to )) of Camilo. 
Although the manual from the website of Kamala ...he's going fine. But due to the fact that you are Campiglio in their own way, I can evaluate your project , although I have a great desire. It is a pity of course.

**Comment by openvoips** [comment]
The solution is tested in distributed model and during the testing Kamailio, Multiple Freeswitch and database were installed on individual machines. 

As per your suggestion, we are adding MySQL installation steps.

**Comment by openvoips** [comment]
> 
> 
> Completely not correct installation manual .
> 1.According to this manual is not going to kamailo.
> 2.In the second step with the installation of mariadb should be the early item build kamailo. As with the lack of myqsl-devel, Camilo not be collected.
> Guys if uploaded the manual Assembly his project, then let he although would be the right.
> I specifically put centos 7 full, but..
> still not build of camailo
> Although the manual from the website of kamailo ...he's going fine. But due to the fact that you are camailo in their own way, I can evaluate your project , although I have a great desire. It is a pity of course.

The solution is tested in distributed model and during the testing Kamailio, Multiple Freeswitch and database were installed on individual machines.

As per your suggestion, we are adding MySQL installation steps.

**Comment by Madji** [comment]
Too bad I can't fully appreciate your opensource project

**Comment by openvoips** [comment]
Install the libjson* before kamailio compilation

> 
> install -m 755 app_python3.so /home/OV500/LB/lib64/kamailio/modules
> Package json-c was not found in the pkg-config search path.
> Perhaps you should add the directory containing `json-c.pc' to the PKG_CONFIG_PATH environment variable No package 'json-c' found Package json-c was not found in the pkg-config search path. Perhaps you should add the directory containing `json-c.pc'
> to the PKG_CONFIG_PATH environment variable
> No package 'json-c' found
> CC (gcc) [M nsq.so] nsq_reader.o
> In file included from nsq_reader.c:28:0:
> nsq_reader.h:30:18: фатальная ошибка: json.h: Нет такого файла или каталога
> #include <json.h>
> 
> Centos7 minimal

**Comment by kanand81** [comment]
I think you missed to install basic packages. if you want help in installation; Please let us know on openvoips@gmail.com email address.  I will help on installation. you can also ping my skype-id akumardayal 


> 
> Too bad I can't fully appreciate your opensource project

**Comment by Madji** [comment]
Hello, I really wanted to help everyone in my power. So as tried to assess your project but faced wrong written manual on quick on your site. 

Further I explain that:
The following command 
yum install -y luarocks & & luarocks install lua-cjson yasm nor nasm wget curl git bind-utils ntpdate systemd net-tools whois sendmail sendmail-cf mlocate 

it can't be done exactly the way it should but it should look like this 

yum install -y luarocks & & luarocks install lua-cjson 
yum install -y yasm nor nasm curl wget git bind-utils ntpdate, systemd net-tools whois sendmail sendmail-cf mlocate

Secondly:
cd /usr/local/src/
rm-rf /usr/local/src/kamailio
git clone --depth 1 --no-single-branch git://git.kamailio. org/kamailio kamailio
git checkout-b 4.6 origin/4.6
cd /usr/local/src/kamailio

there are mixed steps 

it must be 

cd /usr/local/src/
rm-rf /usr/local/src/kamailio
git clone --depth 1 --no-single-branch git://git.kamailio. org/kamailio kamailio
cd /usr/local/src/kamailio
git checkout-b 4.6 origin/4.6

gives an error that it is impossible to switch to this brunch 

Thirdly 
I think the team 
git checkout-b 4.6 origin/4.6
it must be
git checkout-b 4.6 

But before that you forgot in the list of dependencies to do something similar 
yum install python3-devel json-devel json-c-devel 

Only after installing these dependencies will kamailio build.



The next step cloning the freeswitch repository requires authorization.... 
git clone-b v1.6. 8 https://freeswitch.org/stash/scm/fs/freeswitch.git freeswitch
I think it would be easier 
after
git clone-b v1.6. 8 https://github.com/signalwire/freeswitch.git freeswitch


I believe that if the manual is laid out in public access ...so he must be a worker. 

And to close iisue referring to the fact that I missed installation of the main packages.....

So I repeat that the installation was on your manual, on a clean system centos7

**Comment by kanand81** [comment]
I added your suggestions to installation documents. I would request you to join the OV500 community and add your suggestion directly to the community.
> 
> Hello, I really wanted to help everyone in my power. So as tried to assess your project but faced wrong written manual on quick on your site.
> 
> Further I explain that:
> The following command
> yum install -y luarocks & & luarocks install lua-cjson yasm nor nasm wget curl git bind-utils ntpdate systemd net-tools whois sendmail sendmail-cf mlocate
> 
> it can't be done exactly the way it should but it should look like this
> 
> yum install -y luarocks & & luarocks install lua-cjson
> yum install -y yasm nor nasm curl wget git bind-utils ntpdate, systemd net-tools whois sendmail sendmail-cf mlocate
> 
> Secondly:
> cd /usr/local/src/
> rm-rf /usr/local/src/kamailio
> git clone --depth 1 --no-single-branch git://git.kamailio. org/kamailio kamailio
> git checkout-b 4.6 origin/4.6
> cd /usr/local/src/kamailio
> 
> there are mixed steps
> 
> it must be
> 
> cd /usr/local/src/
> rm-rf /usr/local/src/kamailio
> git clone --depth 1 --no-single-branch git://git.kamailio. org/kamailio kamailio
> cd /usr/local/src/kamailio
> git checkout-b 4.6 origin/4.6
> 
> gives an error that it is impossible to switch to this brunch
> 
> Thirdly
> I think the team
> git checkout-b 4.6 origin/4.6
> it must be
> git checkout-b 4.6
> 
> But before that you forgot in the list of dependencies to do something similar
> yum install python3-devel json-devel json-c-devel
> 
> Only after installing these dependencies will kamailio build.
> 
> The next step cloning the freeswitch repository requires authorization....
> git clone-b v1.6. 8 https://freeswitch.org/stash/scm/fs/freeswitch.git freeswitch
> I think it would be easier
> after
> git clone-b v1.6. 8 https://github.com/signalwire/freeswitch.git freeswitch
> 
> I believe that if the manual is laid out in public access ...so he must be a worker.
> 
> And to close iisue referring to the fact that I missed installation of the main packages.....
> 
> So I repeat that the installation was on your manual, on a clean system centos7
