### ISSUE TITLE
Issue On Login Page After Installation

### ISSUE THREAD

**Issue by amitiyer** [openvoips/OV500#3]
Hello,

I have used the installation guide and when i try to login i get the below error.

![image](https://user-images.githubusercontent.com/25080311/68755976-6111af80-062f-11ea-8c79-69f79332f995.png)

**Comment by openvoips** [comment]
Hello Amit,

Please use below cmd

rm -rf /home/OV500/portal/application/config/database.php

echo "<?php
defined('BASEPATH') OR exit('No direct script access allowed');
\$active_group = 'default';
\$query_builder = TRUE;
\$db['default'] = array(
'dsn' => 'mysql:host=localhost;dbname=switch',
'hostname' => '',
'username' => 'ovswitch',
'password' => 'ovswitch123',
'database' => '',
'dbdriver' => 'pdo',
'dbprefix' => '',
'pconnect' => TRUE,
'db_debug' => TRUE,
'cache_on' => FALSE,
'cachedir' => '',
'char_set' => 'utf8',
'dbcollat' => 'utf8_general_ci',
'swap_pre' => '',
'encrypt' => FALSE,
'compress' => FALSE,
'stricton' => FALSE,
'failover' => array()
);
\$db['cdrdb'] = array(
'dsn' => 'mysql:host=localhost;dbname=switchcdr',
'hostname' => '',
'username' => 'ovswitch',
'password' => 'ovswitch123',
'database' => '',
'dbdriver' => 'pdo',
'dbprefix' => '',
'pconnect' => FALSE,
'db_debug' => FALSE,
'cache_on' => FALSE,
'cachedir' => '',
'char_set' => 'utf8',
'dbcollat' => 'utf8_general_ci',
'swap_pre' => '',
'encrypt' => FALSE,
'compress' => FALSE,
'stricton' => FALSE,
'failover' => array(),
'save_queries' => TRUE
);">>/home/OV500/portal/application/config/database.php





Have a nice moment always!

Thanks and Regards,
Seema Anand

[image: http://openvoips.com/] <http://openvoips.com/>
Email: openvoips@gmail.com
Skype: simadayal
Web: https://ov500.openvoips.org

**Comment by amitiyer** [comment]
Thank you, That Solved the problem.
