### ISSUE TITLE
CDR Page Blank

### ISSUE THREAD

**Issue by amitiyer** [openvoips/OV500#4]
Hello,

I tried making a call and the call failed. When i went to check the CDR (https://serverIP/reports/AnsCalls) i get a blank page, it's the same for Failed calls too.

**Comment by openvoips** [comment]
I think you have missed to setup the Routing API. and your call is not
processed.

If your installation is correct,  you can enable the API log in
"/home/OV500/portal/api/config.php" file like

define('LOGWRITE', '1');

Also verify " /home/OV500/portal/api/log" folder is available or not if it
is not available please create and assign the write permission.  There you
can get the dialplan XML in API log  that means configuration is ok.

My skype is "akumardayal" and you can ping me to get the live support.
