### ISSUE TITLE
What's the init login account and password for OV500?

### ISSUE THREAD

**Issue by sparklezou** [openvoips/OV500#43]
Hi Sir/Madam,

I trying to install the OV500. When done, I could NOT login the web. I tried the "admin""123456". But don't work.

What's the init login account and password?

Thanks!

BR,
Sparkle Zou

**Comment by openvoips** [comment]
Try. ***@***.***

**Comment by sparklezou** [comment]
Hi，

Tryed username"***@***" password "***" still NOT work. 

I'm NOT family with web server.  How to check it?

Thanks!

BR,
Sparkle Zou

**Comment by openvoips** [comment]
try   ***@***.***

Have a nice moment always!

Thanks and Regards,
Anand Kumar

[image: http://openvoips.com/] <http://openvoips.com/>
Email: ***@***.***
Skype: ***@***.***
Web: https://ov500.openvoips.org

**Comment by openvoips** [comment]
default web access is  admin /  Ov500@786
