### ISSUE TITLE
Cant delete account / Page not loading normal / Ticket page nog loading / Pre-paid and Post-paid Billing?

### ISSUE THREAD

**Issue by MichaelSTK** [openvoips/OV500#47]
Hi all!

Installed on a VPS with proxmox in a VM 

I have followed this installation guide
https://powerpbx.org/ov500-voip-billing-v1-debian-v11-freeswitch-v110-kamailio-v5-install-guide-v1

Logged in with the main account created during installation (admin)

- Not possible to delete another admin account
- Not possible to delete a reseller account
- When a customer presses the "Support HelpDesk" button, an error code/white page appears
- I have created 1 reseller account, if I press "Service Edit" then the page is half loaded (without layout)
There was also already 1 reseller test account created during the installation, and I can just go to "service edit" there without any problems
- Where to find Pre-paid and Post-paid Billing?
- No Invoice and billing in my version

If I need to show logs or anything I like to be told what commands to enter in the console

Kind regards
Michael

**Comment by openvoips** [comment]
The updated release has depreciated the helpdesk module
