### ISSUE TITLE
Cannot See Added Rates

### ISSUE THREAD

**Issue by amitiyer** [openvoips/OV500#5]
Hi, 
I have added the customer rates but i cannot see it on the Rates Page, Also when i try to add it again. it says duplicate entry

![image](https://user-images.githubusercontent.com/25080311/68761603-6c1e0d00-063a-11ea-9f3d-ece9d00dd847.png)
![image](https://user-images.githubusercontent.com/25080311/68761622-7a6c2900-063a-11ea-94f7-b0ceb1e4d73d.png)

**Comment by kanand81** [comment]
As per shared screenshot, you are adding the Rate in different rate card
and searching in different rate card. Also you are running GUI in
development mode.

System is creating CDR tables at time of call processing. So you need to
setup the rate and tariff properly.  If you unable to do that please let me
know. My Skype ID is akumardayal
