### ISSUE TITLE
Error sql table

### ISSUE THREAD

**Issue by Madji** [openvoips/OV500#6]
Error import sql table

[root@ats src]# mysql switch < /usr/local/src/OV500/config/database/switch.sql
ERROR 1064 (42000) at line 526: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '`id` int(11) NOT NULL AUTO_INCREMENT,
`account_id` varchar(30) DEFAULT NULL,
' at line 1
[root@ats src]#

Mariadb -10

**Comment by kanand81** [comment]
schema issue fixed
--
Anand Kumar
Mobile: +919949800228

**Comment by Madji** [comment]
Yes thank you. Imported normally. No problem
