### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Madji** [openvoips/OV500#7]
Is it even possible to use it in life as a billing? 
It seems to me that this billing, just a test. This cannot be used in real life(Production), much less for traffic sales. A terrible jumble of different components. 
Strange logic when setting up tariffs and other things. Now it is clear why you conduct courses on setting this up. Because it first needs to be set so to make it work and then understand how to configure. Believe me, I dealt with Softswitch and billing, including paid ones. So boldly say on here is this sell traffic cannot be.

**Comment by kanand81** [comment]
This project is ready to use. Here, solution is build for distributed
architecture with loadbalancer and it is used by us guys in over network.

**Comment by Madji** [comment]
Well.. let's make another attempt to make it work
